---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ypeer.azurecr.io/y-peer-staging/frontend:v_%BUILD_NUMBER%
          resources:
            limits:
              cpu: 350m
              memory: 250Mi
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - name: pod-port
              containerPort: 443

          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            # initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
            timeoutSeconds: 5

          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            # initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
            timeoutSeconds: 5